app/urls.py
#!/usr/bin/env python3
# -*-coding:utf-8 -*-
# __author__:Jonathan
# email:nining1314@gmail.com
from django.conf.urls import url
from app import views

urlpatterns = [
    url(r'^app/customer_list/$', views.customer_list),
    url(r'^(\w+)/(\w+)/(\d+)/change/$', views.customer_obj_change, name="table_obj_change"),
    url(r'^(\w+)/(\w+)/add/$', views.customer_obj_add, name="table_obj_add"),
    url(r'^(\w+)/(\w+)/(\d+)/delete/$', views.customer_object_del, name="object_del"),

    url(r'^app/customer_followup_list/$', views.customer_followup_list),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mysite import views

urlpatterns = [

    url(r'^$', views.index),
    url(r'^login/$', views.account_login),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/$', views.dashboard),
    url(r'^logout/', views.account_logout),
    url(r'^api/', include('app.rest_urls')),
    url(r'^luffyadmin/', include('luffyAdmin.urls')),
    url(r'^app/', include('app.urls')),
    url(r'^test/', views.test)
]

app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class Source(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class Customer(models.Model):
    name = models.CharField(verbose_name=u'名称', max_length=64, blank=True, null=True)
    qq = models.CharField(verbose_name='QQ',max_length=64, blank=True, null=True, unique=True)
    weixin = models.CharField(max_length=64, blank=True, null=True, unique=True)
    phone = models.BigIntegerField(blank=True, null=True, unique=True)
    email = models.EmailField(blank=True, null=True)
    source = models.ForeignKey('Source')
    referal_from = models.ForeignKey('Account', blank=True, null=True, related_name='my_referal')
    consult_courses = models.ManyToManyField("Course")
    content = models.TextField(u'首次咨询内容/客户详情')
    status_choices = (
        (0, '已报名'),
        (1, '已退费'),
        (2, '未报名')
    )
    status = models.SmallIntegerField(u'状态', choices=status_choices, default=2)
    tags = models.ManyToManyField('Tag', blank=True)
    consultant = models.ForeignKey('Account', related_name='my_consultant')
    date = models.DateTimeField(auto_now_add=True)

    source.verbose_name = u'来源'
    consultant.verbose_name = u'咨询老师'

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "客户信息表"
        verbose_name_plural = "客户信息表"


class PaymentRecord(models.Model):
    customer = models.ForeignKey('Customer')
    class_list = models.ForeignKey('ClassList')
    payment_method_choices = (
        (0, '现金'),
        (1, '微信'),
        (2, '支付宝'),
        (3, '刷卡'),
        (4, '学生贷款'),
    )
    payment_method = models.SmallIntegerField(choices=payment_method_choices)
    payment_type_choices = (
        (0, '报名费'),
        (1, '学费'),
        (2, '退费'),
    )
    payment_type = models.SmallIntegerField(choices=payment_type_choices)
    amount = models.FloatField()


class CustomerFollowUp(models.Model):
    """跟踪记录"""
    customer = models.ForeignKey('Customer')
    content = models.TextField()
    consultant = models.ForeignKey('Account')
    date = models.DateTimeField(auto_now_add=True)
    status_choices = (
        (0, '绝不考虑'),
        (1, '短期内不考虑'),
        (2, '已在其他机构报名'),
        (3, '2周内报名'),
        (4, '已报名'),
        (5, '已试听'),
    )
    status = models.IntegerField(choices=status_choices)

    def __str__(self):
        return self.customer.name

class Course(models.Model):
    name = models.CharField(max_length=128, unique=True)
    period = models.IntegerField(u'周期(月)')
    price = models.FloatField()
    outline = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "课程信息表"
        verbose_name_plural = "课程信息表"


class Branch(models.Model):
    """校区"""
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    course = models.ForeignKey('Course')
    branch = models.ForeignKey('Branch')
    semester = models.IntegerField(u'学期')
    contract = models.ForeignKey('Contract')
    class_type_choices = (
        (0, '周末'),
        (1, '脱产'),
        (2, '网络'),
    )
    class_type = models.IntegerField(choices=class_type_choices)
    max_student_num = models.IntegerField(default=80)
    teachers = models.ManyToManyField('Account')
    start_date = models.DateField(u'开班日期')
    end_date = models.DateField(u'结业日期', blank=True, null=True)

    def __str__(self):
        return "%s(%s)" % (self.course, self.semester)

    class Meta:
        unique_together = ('course', 'branch', 'semester', 'class_type')
        verbose_name = "班级信息表"
        verbose_name_plural = "班级信息表"


class CourseRecord(models.Model):
    """上课记录"""
    class_list = models.ForeignKey('ClassList')
    day_num = models.IntegerField(u'节次')
    name = models.CharField(max_length=128)
    teacher = models.ForeignKey('Account')
    has_homework = models.BooleanField(default=True)
    homework_requirement= models.TextField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s(%s)-%s" % (self.class_list, self.day_num, self.name)

    class Meta:
        unique_together = ('class_list', 'day_num')


class Enrollment(models.Model):
    """已报名班级"""
    account = models.ForeignKey('Account')
    class_list = models.ForeignKey('ClassList')
    date = models.DateTimeField(auto_now_add=True)


class StudyRecord(models.Model):
    """学习记录"""
    student = models.ForeignKey('Account')
    course_record = models.ForeignKey('CourseRecord')
    score_choices = (
        (100, 'A+'),
        (90, 'A'),
        (85, 'B+'),
        (70, 'B'),
        (65, 'C+'),
        (60, 'C'),
        (40, 'C-'),
        (-50, 'D'),
        (0, 'N/A'),
        (-100, 'COPY')
    )
    score = models.IntegerField(choices=score_choices)
    show_status_choices = (
        (0, '正常签到'),
        (1, '迟到'),
        (2, '缺勤'),
        (3, 'N/A')
    )
    show_status = models.IntegerField(choices=show_status_choices)
    comment = models.TextField(u'批注', null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('student', 'course_record')


class Contract(models.Model):
    name = models.CharField(max_length=128, unique=True)
    content= models.TextField(u'合同内容')
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


class Role(models.Model):
    """角色：更关注获取menu列表"""
    name = models.CharField(max_length=64, unique=True)
    menus = models.ManyToManyField('Menu', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "角色菜单控制"
        verbose_name_plural = "角色菜单控制"


class Menu(models.Model):
    """一级菜单"""
    name = models.CharField(max_length=64)
    url_type_choices = (
        (0, 'absolute'),
        (1, 'relative'),
    )
    url_type = models.IntegerField(choices=url_type_choices,default=1)
    url = models.CharField(max_length=128)
    order = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ('url', 'url_type')
        verbose_name = "一级菜单"
        verbose_name_plural = "一级菜单"

class SubMenu(models.Model):
    """二级菜单"""
    menu = models.ForeignKey('Menu')
    name = models.CharField(max_length=64)
    url_type_choices = (
        (0, 'absolute'),
        (1, 'relative'),
    )
    url_type = models.IntegerField(choices=url_type_choices, default=1)
    url = models.CharField(max_length=128)
    order = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ('url', 'url_type')
        verbose_name = "二级菜单"
        verbose_name_plural = "二级菜单"


class Account(models.Model):

    username = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.username


class MyUserManager(BaseUserManager):
    def create_user(self, email, name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            name=name,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class Account1(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    name = models.CharField(max_length=32)
    role = models.ForeignKey("Role", blank=True, null=True)
    customer = models.OneToOneField("Customer", blank=True, null=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        # The user is identified by their email address
        return self.name

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->

    <meta name="description" content="">
    <meta name="author" content="Jonathan">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">

    <title>客户管理系统</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/dashboard.css" rel="stylesheet">
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
        .subMenuChosen{
            background-color: #c2c2c2;
        }
    </style>
    {% block header %}

    {% endblock %}

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#" style="color: white">客户管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/luffyadmin/" style="color: rgba(255,255,255,0.75)">控制面板</a></li>
            <li><a href="#" style="color: rgba(255,255,255,0.75)">设置</a></li>
            <li><a href="#" style="color: rgba(255,255,255,0.75)">个人信息</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color: rgba(255,255,255,0.75)">{{ request.user.name }} <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/logout/">Logout</a></li>
              </ul>
            </li>

          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="搜索...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
{#          <ul class="nav nav-sidebar">#}
{#            <li class="active">#}
{#                <a href="#" class="header">一级菜单</a>#}
{#                <ul class="nav hidden">#}
{#                    <li class="subMenu"><a href="#" style="padding-left: 30px" >二级菜单1</a></li>#}
{#                    <li class="subMenu"><a href="#" style="padding-left: 30px">二级菜单2</a></li>#}
{#                    <li class="subMenu"><a href="#"  style="padding-left: 30px">二级菜单3</a></li>#}
{#                </ul>#}
{#            </li>#}
{#          </ul>#}
{#          <ul class="nav nav-sidebar">#}
{#            <li class="active">#}
{#                <a href="#"  class="header">一级菜单</a>#}
{#                <ul class="nav hidden">#}
{#                    <li class="subMenu"><a href="#" style="padding-left: 30px">二级菜单</a></li>#}
{#                    <li class="subMenu"><a href="#" style="padding-left: 30px">二级菜单</a></li>#}
{#                    <li class="subMenu"><a href="#" style="padding-left: 30px">二级菜单</a></li>#}
{#                </ul>#}
{#            </li>#}
{#          </ul>#}
{#          <ul class="nav nav-sidebar">#}
{#            <li class="active">#}
{#                <a href="/luffyadmin/"  class="header">定制框架</a>#}
{#            </li>#}
{#          </ul>#}

            {%  for menu in  request.user.role.menus.all %}
                <ul class="nav nav-sidebar">
                    <li class="active">
                         <a href="{{ menu.url }}" class="header">{{ menu.name }} </a>
                    {% if menu.submenu_set.all %}
                        <ul class="nav hidden">
                            {% for submenu in menu.submenu_set.all %}
                            <li class="subMenu" >
                                <a href="{% if submenu.url_type == 0 %}{{ submenu.url }}{% else %}{{ submenu.url }}{% endif %}">{{ submenu.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    </li>
                </ul>

            {% endfor %}


        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block content %}

            <h1>content</h1>

            {% endblock %}

        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="/static/js/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
    <script src="/static/layer/layer.js"></script>

    <!-- 左侧菜单js -->
    <script>
        $(".header").click(function () {
            $(this).parent().parent().siblings('ul').children('li').children('ul').addClass('hidden');
            $(this).next('ul').removeClass('hidden');
        });
        $(".subMenu").click(function () {
            $(this).addClass("subMenuChosen");
            $(this).siblings('li').removeClass("subMenuChosen");
        });
       $(".subMenu").hover(function () {
           $(this).css('border-left', '#428bca solid 3px')
       },function () {
            $(this).css('border-left', '')
       })
    </script>

</body>



</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>index</h1>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<!-- saved from url=(0038)http://v3.bootcss.com/examples/signin/ -->
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">

    <title>后台管理系统</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/signin.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

<body>
    <div class="container">

      <form class="form-signin" method="post">
          {% csrf_token %}
        <h2 class="form-signin-heading">登录界面</h2>
        <label for="inputEmail" class="sr-only">登录邮箱</label>
        <input type="email" id="inputEmail" name='username' class="form-control" placeholder="登录邮箱" required="" autofocus="">
        <label for="inputPassword" class="sr-only">登录密码</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="登录密码" required="">
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> 记住我
          </label>
        </div>
        <input class="btn btn-lg btn-primary btn-block" type="submit" value="登录"/>
      </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
  

</body>

</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="/login/" method="post">
    用户名：<input name="username" type="text"/><br/>
    密码:<input name="password" type="password"/>
    <input type="submit" value="提交"/>
</form>
</body>
</html>